// Code generated by Slice Machine. DO NOT EDIT.

import HeroTagline from './HeroTagline/index.svelte';
import ProductList from './ProductList/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	hero_tagline: HeroTagline,
	product_list: ProductList,
	rich_text: RichText
};
